spring:
  application:
    name: notification-manager
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      database: notification
      port: 27017
      host: localhost
  mail:
    host: smtp.gmail.com
    port: 587
    username: memeussr@gmail.com
    password: memeussr228
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    consumer:
      # todo: consider changing localhost to address of kafka server
      bootstrap-servers: localhost:9092
      group-id: notifications
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost


app:
  tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
  tokenExpirationMsec: 864000000

server:
  port: 8082