spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: meeton-core
          uri: lb://meeton-core
          predicates:
            - Path=/meeton-core/**,/ws/comment/**
        - id: authentication-manager
          uri: lb://authentication-manager
          predicates:
            - Path=/authentication-manager/**,/oauth2/**
        - id: notification-manager
          uri: lb://notification-manager
          predicates:
            - Path=/notification-manager/**,/ws/notification/**
        - id: rating-manager
          uri: lb://rating-manager
          predicates:
            - Path=/rating-manager/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

logging:
  level:
    org.springframework: DEBUG

server:
  port: 8989