spring:
  application:
    name: authentication-manager
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      database: authentication_users
      port: 27017
      host: localhost
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 9387373968-013ktbioq3s0remtt09mgmpup4lv996g.apps.googleusercontent.com
            client-secret: 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
            # todo: change localhost to public api-gateway url after deploying
            redirectUri: "http://localhost:8989/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          github:
            client-id: Iv1.043f3e4e6820d9c2
            client-secret: 6505f5b8566fc4099f7f4e8f0bafb68015bd2082
            redirectUri: "http://localhost:8989/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost


app:
  tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
  tokenExpirationMsec: 864000000
  authorizedRedirectUris:
    - http://localhost:3000/oauth2/redirect
  meeton-core-url: http://API-GATEWAY

server:
  port: 8081