@startuml

actor User

User -> UI:  Нажимает "Регистрация"
UI --> User: Страница для ввода данных
User -> UI:  Вводит логин, email, пароль
User -> UI:  Нажимает "Зарегистрироваться"
UI -> AM:    Запрос на регистрацию
AM -> AM:    Проверка данных на корректность
alt Пользователь с таким логином и email не найден в БД
    AM -> MongoDB: Сохраниение данных в БД
    MongoDB --> AM: Пользователь сохранен
    AM -> "meeton-core": Данные о новом пользователе
    "meeton-core" -> PostgreDB: Сохраниение данных в БД
    PostgreDB --> "meeton-core": Пользователь сохранен
    AM --> UI:   Пользователь зарегистрирован
    UI --> User: Страница входа
    User -> User: Подтверждает почту
    User -> UI:  Вводит логин, пароль
    UI -> AM:    Запрос на авторизацию
    AM -> AM:    Проверка данных на корректность
    AM -> AM:    Генерация JWT и формирование ответа
    AM --> UI:   JWT для дальнейшей работой с системой
    UI --> User: Личный кабинет пользователя
else Найден пользователь с таким логином или email
    AM -> AM: Проверка провайдера у найденного пользователя
    alt Внутренний провайдера
        AM --> UI: Пользователь с таким логином/email уже зарегистрирован
    else Внешний провайдера
        AM --> UI: Этот пользователь уже зарегистрирован через Google/Github
end
UI --> User: Информация об ошибке

end
@enduml