@startuml

actor User

User -> UI: Нажимает "Войти в систему через Google/Github"
UI -> AM:   Запрос на аутентификацию\nчерез внешнего провайдера
AM -> "Google/Github": Запрос страницы для входа в аккаунт
"Google/Github" -> AM: Страница для входа в аккаунт
AM --> UI:
UI --> User:
User -> UI: Ввод данных для входа в аккаунт Google или Github
UI -> "Google/Github": Отправка данных для входа
"Google/Github" -> "Google/Github": Валидация данных
alt Успешная авторизация
    "Google/Github" --> AM: Пользователь авторизован
    alt Первый вход пользователя через стороннего провайдера
        AM -> AM: Заполнение данных
        AM -> MongoDB: Сохраниение данных в БД
        MongoDB --> AM: Пользователь сохранен
        AM -> "meeton-core": Данные о новом пользователе
        "meeton-core" -> PostgreDB: Сохраниение данных в БД
        PostgreDB --> "meeton-core": Пользователь сохранен
    else Пользователь уже был авторизован ранее
        AM -> AM: Проверка корректности ответа от провайдера
    end
        AM -> AM: Генерация JWT и формирование ответа
        AM --> UI: JWT для дальнейшей работой с системой
        UI --> User: Личный кабинет пользователя
else Неуспешная попытка авторизации
    "Google/Github" --> AM: Пользователь НЕ авторизован
    AM --> UI: Ошибка при авторизации
    UI --> User:
end

@enduml