spring:
  application:
    name: meeton-core
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/meeton
    username: root
    password: root
  jpa:
    generate-ddl: true
  kafka:
    consumer:
      # todo: consider changing localhost to address of kafka server
      bootstrap-servers: localhost:9092
      group-id: new_user_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  jwtSecret: 926D96C90030DD58429D2751AC1BDBBC
  api-gateway-url: http://API-GATEWAY

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost