spring:
  application:
    name: meeton-core
  datasource:
    url: jdbc:postgresql://localhost:5432/meeton
    username: root
    password: root
  jpa:
    generate-ddl: true
  mail:
    host: smtp.gmail.com\
    port: 687
    username: kirill.pet13@gmail.com
    password: uecchpnypznhlycj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwtSecret: 926D96C90030DD58429D2751AC1BDBBC
  jwtExpirationMs: 864000000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

