spring:
  application:
    name: meeton-core
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/meeton
    username: root
    password: root
  jpa:
    generate-ddl: true

app:
  jwtSecret: 926D96C90030DD58429D2751AC1BDBBC
  api-gateway-url: http://API-GATEWAY

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost